### ISSUE TITLE
Feat: Support query logs in parallel and with multiple RPC url endpoints

### ISSUE THREAD

**Issue by quangkeu95** [darkforestry/amms-rs#100]
# Describe the feature
- In order to reduce query time, we could run the log query process in parallel with multiple tokio tasks.
- Also adding support for passing multiple RPC url endpoints into any function that need to query logs data, thus we could avoid rate limit from the third party node provider.

**Comment by 0xKitsune** [comment]
Cleaning up old issues and closing this one for now. With the upcoming `0.7.0` release, this can be specified at the provider layer. For example, you could use a provider that leverages multiple RPC endpoints, without any changes needed in `amms-rs`. Additionally, there is no longer throttle logic in the lib either as this is also specified at the provider layer.

[Here is an example](https://github.com/darkforestry/amms-rs/blob/0.7.0/examples/state_space_builder.rs#L22-L27) where the provider is specified with a `ThrottleLayer` and `RetryLayer`.

Feel free to open an issue in the future if there is anything that would be helpful to have in the lib!
