### ISSUE TITLE
Throttling 

### ISSUE THREAD

**Issue by digitalmnt** [darkforestry/amms-rs#107]
Heyo! The ol `cfmm-rs` project you all created had a throttling feature for methods like `sync_pools_from_checkpoint_with_throttle`. Do you all have any interest in implementing this for methods like `populate_tick_data`. I'm running into issues synching pools on arbitrum via alchemy rpc and would be happy to put this together!

This is what I am running into

```
MiddlewareError(MiddlewareError(MiddlewareError(JsonRpcClientError(JsonRpcError(JsonRpcError { code: 429, message: "Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message
```

**Comment by 0xKitsune** [comment]
Hey @digitalmnt thanks for opening this issue. Coincidentally I just created a `ThrottleProvider` that wraps any provider, allowing you to throttle any Ethers providers/middleware without needing to change any core logic within a codebase. 

I am going to build out the lib further to make it a bit more extensible/generalized but this should solve any API limit issues you are hitting.
