### ISSUE TITLE
 Choice of RwLock<HashMap> over DashMap for Concurrent Access

### ISSUE THREAD

**Issue by nabeel99** [darkforestry/amms-rs#109]
Hello,

I've been exploring the ammrs crate, particularly focusing on the StateSpaceManager and its use of RwLock<HashMap>. In my current scenario, which involves a pattern of frequent short read and write operations, I'm considering the efficiency of different concurrent data structures. DashMap, with its sharding mechanism and lock-free reads, appears to be a strong candidate for such workloads.

I'm curious if there was a specific reason behind choosing Arc<RwLock<HashMap>> over something like DashMap. Are there particular performance considerations, compatibility issues, or other factors that influenced this decision? If these considerations aren't a constraint, would you be open to a discussion on potentially migrating the StateSpaceManager to use DashMap to possibly enhance its concurrency handling?

Thank you for your work on this crate and for your time in addressing this inquiry.

**Comment by 0xKitsune** [comment]
Hey thanks for opening this issue and sorry for the delay. Originally `DashMap` was explored but never implemented, however there was not a specific reason other than using types out of the std lib while in early development. There are quite a few updates/upgrades to the codebase that can be made and it would be great to see some benches comparing using `RwLock<HashMap>` to `DashMap`.

**Comment by 0xKitsune** [comment]
Closing for now, feel free to open another issue or a PR if you would like to bench the two implementations.
