### ISSUE TITLE
429 rpc error

### ISSUE THREAD

**Issue by Klugekluge67** [darkforestry/amms-rs#128]
### Describe the feature you would like

tried as is with Alchemy and Quicknode rpc. Got 429 error on artemis/collector.rs file
Any way to fix.

**Comment by 0xKitsune** [comment]
Thanks for opening an issue! 

429 is likely indicating that there are too many requests being sent in a short time horizon. In the example, the [amms are first synced](https://github.com/darkforestry/amms-rs/blob/main/examples/artemis-collector.rs#L48-L49), however the middleware that is used does not have a throttle. 

The easiest fix should be to use a [throttled provider](https://github.com/0xKitsune/ethers-throttle/blob/main/examples/throttled-http-provider.rs#L14-L15). Feel free to give it a shot or open a PR with this if you would like and let me know if you run into anything else.

**Comment by kvnkmth** [comment]
this is an issue  in alloy too. but  throttled provider is in ethers
