### ISSUE TITLE
Mistake in artemis collector example

### ISSUE THREAD

**Issue by cuongquangnam** [darkforestry/amms-rs#130]
https://github.com/darkforestry/amms-rs/blob/6020dc0ac6c90be019e1dcbfef283134316e5c87/examples/artemis-collector.rs#L152

This should be 
` 
     amm_weight_0 * target_amm_weight_1
`
The same can be said for the subsequent multiplication

**Comment by 0xOsiris** [comment]
Hey, thanks for opening this. You are right! Feel free to open a PR on this as well, otherwise I can get this updated later tonight.
