### ISSUE TITLE
balancer pools 

### ISSUE THREAD

**Issue by iht76** [darkforestry/amms-rs#143]
### Describe the feature you would like

How difficult would it be to add different types of pools like balancer and solidly for example?

**Comment by cuongquangnam** [comment]
Yeah, I am also curious about the possibility of supporting other types of pools

**Comment by 0xKitsune** [comment]
Thanks for opening an issue. Adding an AMM is relatively straightforward and [documented in this guide](https://github.com/darkforestry/amms-rs/blob/main/docs/addingAnAMM.md). The guide may need some updating but the general steps are still the same. 

For pools with more than 2 tokens, there would need to be a more significant change to how the AMM trait works. We have discussed how best to approach pools with an arbitrary number of tokens in the past, but we never finalized a design. Feel free to suggest any ideas, the lib will eventually be updated to support pools with any number of tokens.
