### ISSUE TITLE
feat: alloy migration

### ISSUE THREAD

**Issue by 0xDmtri** [darkforestry/amms-rs#146]
### Describe the feature you would like

Would we want to migrate amms-rs to alloy? Happy to start the work :)

**Comment by 0xKitsune** [comment]
Yes, we are actually getting started on this now! `uniswap-v3-math` [was just upgraded to use alloy](https://github.com/0xKitsune/uniswap-v3-math/commit/b04d478e7b46a4a8b6531b619504ddf63b68ba4e) and we are planning to upgrade `amms-rs` next.

We will open a issue for tracking the migration shortly, feel free to take any of the open items once the issue is opened.

**Comment by 0xDmtri** [comment]
> Yes, we are actually getting started on this now! `uniswap-v3-math` [was just upgraded to use alloy](https://github.com/0xKitsune/uniswap-v3-math/commit/b04d478e7b46a4a8b6531b619504ddf63b68ba4e) and we are planning to upgrade `amms-rs` next.
> 
> We will open a issue for tracking the migration shortly, feel free to take any of the open items once the issue is opened.

Dope, im more than happy to contribute. Tag me plz when u get issue tracker out.

**Comment by 0xDmtri** [comment]
@0xKitsune any chance you had a sec to make some migration tasks?

**Comment by 0xKitsune** [comment]
Thanks for pinging, Ill open an issue later today and tag you here.

**Comment by 0xKitsune** [comment]
@0xDmtri [Here is the tracking issue](https://github.com/darkforestry/amms-rs/issues/151). I think that updating the `amms` module is the best place to start, focusing first on the `AutomatedMarketMaker` trait, then updating each of the various `amms`. 

To avoid compilation errors everywhere, we can temporarily comment out the modules in `lib.rs` that are still using ethers while in the process of upgrading to alloy.

Lets carry the conversation to the open issues, looking forward to this upgrade!
