### ISSUE TITLE
Add `AutomatedMarketMaker` benchmarks 

### ISSUE THREAD

**Issue by 0xKitsune** [darkforestry/amms-rs#179]
Add benchmarks for `UniswapV2Pool`, `UniswapV3Pool` and `ERC4626Vault` for the following functions:

- `sync_from_log`
- `calculate_price`
- `simulate_swap`

**Comment by DeluxeRaph** [comment]
I'm working on a benchmark for UniswapV2Pool  ```sync_from_log``` . Should the test make a rpc call?

**Comment by 0xKitsune** [comment]
Closing for now as this is outdated. We have benches for `simulate_swap` in the upcoming `0.7.0` release. We will re-open an issue once the `0.7.0` changes have been upstreamed to `main`. From there we can add benches for `sync` and `calculate_price` for each pool.
