### ISSUE TITLE
Bug:  Cannot get pool data for ZKSyncERA chain 

### ISSUE THREAD

**Issue by monroeeee** [darkforestry/amms-rs#180]
### Describe the bug

`UniswapV2Pool::new_from_address(pair_address: pair, fee: 0, middleware) ` is not working on the ZKSyncERA chain.
There is a ProviderError  when getting pool data: ` (code: 3, message: Failed to serialize transaction: toAddressIsNull, data: None)`

**Comment by 0xOsiris** [comment]
> ### Describe the bug
> 
> `UniswapV2Pool::new_from_address(pair_address: pair, fee: 0, middleware) ` is not working on the ZKSyncERA chain.
> 
> There is a ProviderError  when getting pool data: ` (code: 3, message: Failed to serialize transaction: toAddressIsNull, data: None)`

Can you share a repro?

**Comment by 0xKitsune** [comment]
Closing this issue for now due to it being stale. Feel free to reopen if you are still having issues!
