### ISSUE TITLE
Feat: Algebra pools

### ISSUE THREAD

**Issue by iht76** [darkforestry/amms-rs#202]
### Describe the feature you would like

I was trying to add Algebra pools following the tutorial, however it didn't work. I am not sure if it is possible, or I didn't do it correctly. (Btw. tutorial needs rewriting. Its not accurate)
Algebra AMM is very similar to Uni v3, with 1 major difference that 1 pool can have different commissions which can be set dynamically.

**Comment by 0xKitsune** [comment]
> (Btw. tutorial needs rewriting. Its not accurate)
Thanks for flagging! We are actually rewriting the tutorials with the upcoming `0.7.0` release. The process of adding a new AMM variant has changed slightly (for the better). 

#235 for reference

**Comment by 0xKitsune** [comment]
Docs related to adding a new AMM have been updated in #252.
