### ISSUE TITLE
Bug: error: failed to run custom build command for `gmp-mpfr-sys v1.6.4`

### ISSUE THREAD

**Issue by iht76** [darkforestry/amms-rs#218]
### Describe the bug

there seems to be a problem when building under windows :

error: failed to run custom build command for `gmp-mpfr-sys v1.6.4`
Windows MSVC target is not supported (linking would fail)

**Comment by 0xKitsune** [comment]
It looks like [this has been an issue with the rug crate](https://stackoverflow.com/questions/63840684/error-failed-to-run-custom-build-command-for-gmp-mpfr-sys-v1-4-0). You may be able to [specify a different build target that works](https://www.reddit.com/r/rust/comments/1c3flgz/comment/kzgmgc6/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button). Feel free to open another issue if you are still running into problems.
