### ISSUE TITLE
Uniswap V3 should sync on a pool's Initialize event

### ISSUE THREAD

**Issue by merolish** [darkforestry/amms-rs#222]
This will allow the pool object to set sqrtPriceX96 and tick. In my own testing if you call simulate_swap before any other swaps have been executed in the pool, it will fail on the price being zero. (Obviously this is rare.) Glad to provide a PR.

**Comment by 0xOsiris** [comment]
Not sure what you mean exactly. The `sqrtPriceX96` is always populated after hitting a `PoolCreated` event through a batch request contract. 

Reference: https://github.com/darkforestry/amms-rs/blob/791fac345822484bf2bed2b4eca0b55589c20cad/src/amm/uniswap_v3/batch_request/mod.rs#L79

This is called during sync. The `PoolCreated` event doesn't hold the price AFAIK

**Comment by merolish** [comment]
Got it. I was considering the use case where I wanted to maintain consistent state in the past for backtesting, but we've figured out an alternate approach. Thanks!
