### ISSUE TITLE
Bug: how long will it take ?

### ISSUE THREAD

**Issue by Aviksaikat** [darkforestry/amms-rs#224]
### Describe the bug

Hi, how long will it take to sync pools ? Is there a way to save the pools data into a file ?

**Comment by 0xKitsune** [comment]
Pool syncing time been greatly improved in the upcoming `0.7.0` release. Sync times depend on the endpoint you are using (local or hosted) and if there are any throttles. Generally, with an unthrottled RPC endpoint from one of the well known RPC providers, the sync times with the changes in `0.7.0` when syncing UniswapV2 and UniswapV3 on Ethereum Mainnet are ~20ish seconds. YMMV depending on the node.

#235 for reference.
