### ISSUE TITLE
Feat: Option to add filters

### ISSUE THREAD

**Issue by Aviksaikat** [darkforestry/amms-rs#233]
### Describe the feature you would like

It would be nice if we have the option to specify certain pools using a filter rather than fetching all the pools

**Comment by captain-l3vi** [comment]
Would be very helpful because what if we want to fetch only say 1000 certain pairs. But for now we have to first sync all the data first.

**Comment by 0xKitsune** [comment]
We are open sourcing a large refactor that will include this functionality. The changes will be migrated to `amms-rs` over the weekend.

**Comment by 0xKitsune** [comment]
This will be[ included in the upcoming `0.7.0` release](https://github.com/darkforestry/amms-rs/blob/0.7.0/examples/filters.rs#L37-L51).  Closing as this is scheduled to be upstreamed to main soon!
