### ISSUE TITLE
Question about spinoff, logging and tracing

### ISSUE THREAD

**Issue by vyorkin** [darkforestry/amms-rs#85]
Hi! I want to submit a PR to `amms-rs` that replaces `spinoff` with log & tracing crates. So it would be possible to get an insight into the execution flow. Also, it seems that `spinoff` is only called at the beginning and the end of top-level functions like `sync_amms` and `discover_factories` and could be moved outside of these functions. This means we can completely remove the `spinoff` or use it only in `examples`.

**Comment by 0xKitsune** [comment]
Hey thanks for opening this issue, adding logging has been something that we have wanted to add but just have not implemented yet so feel free to submit a PR.

For a little insight on the execution flow, check out [this example](https://github.com/darkforestry/amms-rs/blob/main/examples/sync-amms.rs) and checkout the functions that `sync_amms` calls. As a quick summary, this function calls `get_all_amms` on each factory passed in, where then the `populate_amms` function is called to fetch the data from each pool via a call to a contract that batches calls.

For syncing a single pool, you can also initialize a new pool with [`UniswapV2::new_from_address`](https://github.com/darkforestry/amms-rs/blob/main/examples/simulate-swap.rs#L15) or equivalent for other pools. This calls `populate_data` under the hood which is a method implemented to batch fetch data for a single pool.

One thing to note is that UniswapV3 pools sync differently. The library does swap simulation and other operations locally, without the need for an RPC call. To do this, UniswapV3 pools must have all necessary tick data, which requires getting all of the blocks from pool creation and processing the mint/burn logs.

Let me know if you have any specific questions and I will be happy to help.

**Comment by 0xKitsune** [comment]
In the current design, it is necessary to keep the state space synced and ensure that swap calculations are accurate. This is one of the challenges to keeping a local state rather than fetching state for the calculation.

**Comment by 0xKitsune** [comment]
Yes this is exactly the intended design. After syncing, you can create a new `StateSpace` and then use the `[listen_for_state_changes]`(https://github.com/darkforestry/amms-rs/blob/main/src/state_space/state.rs#L193) or equivalent method to keep the pools synced.
