### ISSUE TITLE
Question regarding the implementation of ERC-4626 vaults discovery

### ISSUE THREAD

**Issue by vyorkin** [darkforestry/amms-rs#86]
Hi!
I'm trying to understand the fallback part that selects a different `block_range` (in case of an error).
If there is an error while getting logs then [it parses the error message to get new block numbers](https://github.com/darkforestry/amms-rs/blob/37705262352d0d582f34fd04001c71576c2c847b/src/discovery/erc_4626.rs#L64-L81).

Could you please elaborate on how that part works?
Thank you

**Comment by 0xKitsune** [comment]
Hey we are cleaning up old issues, sorry for never getting back to this. The updated code has been refactored. If you are interested and end up taking a look through the updated logic, let me know if you have any questions.
