### ISSUE TITLE
Refactor: call simulate_swap from simulate_swap_mut

### ISSUE THREAD

**Issue by vyorkin** [darkforestry/amms-rs#89]
I noticed that it should be possible to remove some of the duplicate code by calling the `simulate_swap` from the `simulate_swap_mut` in all 3 modules that are currently implemented

**Comment by 0xKitsune** [comment]
Hey I am cleaning up old issues, the recent refactor has updated most of this logic. Feel free to make a PR if you see something that could be more efficient/cleaner!
