### ISSUE TITLE
Attempt to subtract with overflow

### ISSUE THREAD

**Issue by arb000r** [darkforestry/amms-rs#98]
This issue is still apparent. Syncing from block 0 doesn't fix it :)

Context:
Chain: Optimism
TokenA: 0x4200000000000000000000000000000000000006
TokenB: 0xda10009cbd5d07dd0cecc66161fc93d7c9000da1

Attempting to sync all fee types (100/500/3000/10000).
```thread 'tokio-runtime-worker' panicked at 'attempt to subtract with overflow', /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/amms-0.6.1/src/amm/uniswap_v3/mod.rs:850:13```

_Originally posted by @1saf in https://github.com/darkforestry/amms-rs/issues/84#issuecomment-1728678903_

**Comment by 0xOsiris** [comment]
Hey, I am not able to recreate this. I ran this example on Optimism & was able to sync all amms from the v3 factory without any issues with a basic alchemy node. 

```rs
#[tokio::main]
async fn main() -> eyre::Result<()> {
    //Add rpc endpoint here:
    let rpc_endpoint = std::env::var("OPTIMISM_RPC_ENDPOINT")?;
    let provider = Arc::new(Provider::<Http>::try_from(rpc_endpoint)?);

    let factories = vec![
        //Add UniswapV3
        Factory::UniswapV3Factory(UniswapV3Factory::new(
            H160::from_str("0x1F98431c8aD98523631AE4a59f267346ea31F984")?,
            0,
        )),
    ];

    //Sync pairs
    sync::sync_amms(factories, provider, None, 1000).await?;

    Ok(())
}
```

**Comment by 1saf** [comment]
I will try that. Maybe the difference we are having here is that I am attempting to sync via specific pool addresses

**Comment by 1saf** [comment]
Pool Address - `0x03af20bdaaffb4cc0a521796a223f7d85e2aac31`
Provider - `Optimism Alchemy`

```rust
        match UniswapV3CfmmPool::new_from_address(pool_address, 0, provider).await {
            Ok(cfmm_pool) => {
                println!("Synced");
            }
            Err(why) => {
                log::error!(
                    "Failed to initialise {:#x}. Fee tier {}. Err: {why}",
                    pool.pool_address,
                    fee_tier
                );
            }
        };
```

```
2023-10-05T15:29:18.384174+11:00 INFO xxxx - Initialising pool from address for DAI/WETH/3000/0x03af20bdaaffb4cc0a521796a223f7d85e2aac31
thread 'main' panicked at 'attempt to subtract with overflow', /Users/xxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/amms-0.6.1/src/amm/uniswap_v3/mod.rs:850:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by 1saf** [comment]
```rust
use std::sync::Arc;

use amms::amm::uniswap_v3::UniswapV3Pool;
use common::utils::{crypto::Chain, wallet::get_provider};
use ethers::types::Address;

#[tokio::main]
async fn main() {
    let provider = Arc::new(get_provider(&Chain::Optimism)); // this returns an alchemy optimism provider
    let pool = UniswapV3Pool::new_from_address(
        "0x03af20bdaaffb4cc0a521796a223f7d85e2aac31"
            .parse::<Address>()
            .unwrap(),
        0,
        provider.clone(),
    )
    .await
    .unwrap();
}```

**Comment by 1saf** [comment]
Just did a sync from block 0 of the Uniswap V3 factory and I don't see that pool in the list. Is it skipping certain pools?

**Comment by 1saf** [comment]
Any updates on this?

**Comment by 0xOsiris** [comment]
Hey apologies for the late response on this. I should have some time to investigate early this week

**Comment by 1saf** [comment]
Let me know if I can help. I am trying to get around it by syncing the pool state from subgraph.

**Comment by 0xKitsune** [comment]
Cleaning up old issues and closing for now, we are introducing significant upgrades in the `0.7.0` release that should address all of these issues. Feel free to reopen if you encounter this issue in the future.

#235 for reference
